#!/usr/bin/perl -w

use strict;

printf("\033[3%sm3%sm\033[0m \033[1;3%sm1;3%sm\033[0m \033[4%sm4%sm\033[0m\n", $_, $_, $_, $_, $_, $_) for 0..9;

printf("[3%smx[3%smx[0mx[1;3%smx[1;3%smx[0mx[4%smx[4%smx[0m\n", $_, $_, $_, $_, $_, $_) for 0..9;

__END__
